### ISSUE TITLE
Create a basic flashcard component

### ISSUE THREAD

**Issue by mwhitman189** [mwhitman189/yambo-flashcards#2]
- [ ] The tests have been written
- [ ] The tests all pass

**Comment by justjohnd** [comment]
See attached link for proposed design and tests:

https://www.figma.com/file/spH8XnasXLVLdfq2HA3KiJ/Yambo?node-id=0%3A1

**Comment by justjohnd** [comment]
Test and Feature Specifications:
- 'The preview text is updated dynamically on input'
- 'The "back" button is disabled until the data is entered into the "front" field icon is clicked'
- Typing into the input changes "Preview" to "Save | Cancel". Blank input reverts to 'Preview'
- 'Clicking the "Auto-Generate" button displays the first definition returned from the API'

**Comment by justjohnd** [comment]
Please see link for new design iteration, including adding a "Definition" field. "Specifications" would be the suggested tests for functionality.

https://www.figma.com/file/spH8XnasXLVLdfq2HA3KiJ/Yambo

@KeroseneSlickback , please let me know an email where I can invite you to the Figma project team, so I can give you edit access to the file.
