### ISSUE TITLE
Change site title and description

### ISSUE THREAD

**Issue by mwhitman189** [mwhitman189/yambo-flashcards#5]

**Comment by mwhitman189** [comment]
@justjohnd , @KeroseneSlickback ,
What should the title and description be?

My current uninspired idea:
title -  Yambo Flashcards
description - Flashcard app straight out of Yamagata

**Comment by justjohnd** [comment]
Yambo Flashcards
"Nihongo on the go go"

Eventual viral campaign showing a rainbow coalition of stereotypes around the world standing on mountaintops--the leiderhosen clad portly German, the spear-holding Kenyan, the Inuit in her seal furs, each one calling out in harmony "YammbooOOOOO!" Ricola, anyone? hahaha.
